force-app/main/default/objects/Student_Bulk_Upload__c/Student_Bulk_Upload__c.object-meta.xml
<CustomObject>
    <label>Student Bulk Upload</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Student Bulk Upload Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Bulk Uploads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Bulk_Upload__c/fields/Appinium_Class_ID__c.field-meta.xml
<CustomField>
    <fullName>Appinium_Class_ID__c</fullName>
    <label>Appinium Class ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Bulk_Upload__c/fields/ILT_Class__c.field-meta.xml
<CustomField>
    <fullName>ILT_Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ILT Class</label>
    <referenceTo>redwing__ILT_Class__c</referenceTo>
    <relationshipLabel>Student Bulk Uploads</relationshipLabel>
    <relationshipName>Student_Bulk_Uploads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Bulk_Upload__c/fields/Learning__c.field-meta.xml
<CustomField>
    <fullName>Learning__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Learning</label>
    <referenceTo>redwing__Learning__c</referenceTo>
    <relationshipLabel>Student Bulk Uploads</relationshipLabel>
    <relationshipName>Student_Bulk_Uploads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Bulk_Upload__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>No ILT Class Found</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Bulk_Upload__c/fields/Student_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Student_Email_Address__c</fullName>
    <label>Student Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Student_Bulk_Upload__c/fields/Student_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Student_First_Name__c</fullName>
    <label>Student First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Bulk_Upload__c/fields/Student_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Student_Last_Name__c</fullName>
    <label>Student Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Bulk_Upload__c/fields/Student_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Student_Phone_Number__c</fullName>
    <label>Student Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Student_Bulk_Upload__c/fields/Voucher__c.field-meta.xml
<CustomField>
    <fullName>Voucher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Voucher</label>
    <referenceTo>Voucher__c</referenceTo>
    <relationshipLabel>Student Bulk Uploads</relationshipLabel>
    <relationshipName>Student_Bulk_Uploads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <description>Store the Voucher required to enroll and register for a class</description>
    <label>Voucher</label>
    <nameField>
        <displayFormat>VN {000000}</displayFormat>
        <label>Voucher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voucher</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/fields/ILT_Class__c.field-meta.xml
<CustomField>
    <fullName>ILT_Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ILT Class</label>
    <referenceTo>redwing__ILT_Class__c</referenceTo>
    <relationshipLabel>Voucher</relationshipLabel>
    <relationshipName>Voucher</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Learning_Plan__c.field-meta.xml
<CustomField>
    <fullName>Learning_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Learning Plan</label>
    <referenceTo>redwing__Training_Plan__c</referenceTo>
    <relationshipLabel>Voucher</relationshipLabel>
    <relationshipName>Voucher</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Voucher</description>
    <inlineHelpText>Current Status of Voucher</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Issued</fullName>
                <default>true</default>
                <label>Issued</label>
            </value>
            <value>
                <fullName>Temp Hold</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Claimed</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
            <value>
                <fullName>Pending Cancellation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BulkStudentUpdateTriggerHandler.cls
public with sharing class BulkStudentUpdateTriggerHandler
{
    public static void updateILTClassLoookup (List<Student_Bulk_Upload__c> students)
    {
        Map<String,redwing__ILT_Class__c> iltClassMap = new Map<String,redwing__ILT_Class__c>();

        List<redwing__ILT_Class__c> iltClassList = [SELECT Skedulo_Job_Number__c,
                                                           Id
                                                      FROM redwing__ILT_Class__c
                                                     WHERE Class_Closed_Date__c = null];

        if(iltClassList.size() > 0)
        {
            for(redwing__ILT_Class__c c : iltClassList)
            {
                iltClassMap.put(c.Skedulo_Job_Number__c,c);
            }
        }

        
        for(Student_Bulk_Upload__c s : students)
        {
            redwing__ILT_Class__c iClass = iltClassMap.get(s.Appinium_Class_ID__c);

            if(iClass != null)
            {
                s.ILT_Class__c  = iClass.Id;
                s.Status__c     = 'Created';
            }
            else
            {
                s.ILT_Class__c  = null;
                s.Status__c     = 'No ILT Class Found';
            }

        }

    }

    public static void enrollLearner (List<Student_Bulk_Upload__c> students)
    {

        List<Student_Bulk_Upload__c> sbuList = [SELECT  Id,
                                                		Learning__c,
                                                		Learning__r.Id,
                                                        ILT_Class__c,
                                                        ILT_Class__r.Id,
                                                        Voucher__c,
                                                        Voucher__r.Id,
                                                        ILT_Class__r.Learning_Plan__r.Id,
                                                        Status__c,
                                                        Student_First_Name__c,
                                                        Student_Last_Name__c,
                                                        Student_Phone_Number__c,
                                                        Student_Email_Address__c,
                                                		Is_Processed__c 
                                                   FROM Student_Bulk_Upload__c
                                                  WHERE Is_Processed__c = False 
                                                    AND Id IN : students];

        List<JSONWrapper.Students> studentList = new List<JSONWrapper.Students>();

        Id theLearningPlanId = null;
        Id theOfferingId     = null;
        boolean IsOnline	 = false;
        
        system.debug('sbuList***'+sbuList);

        for(Student_Bulk_Upload__c b : sbuList)
        {
            system.debug('b.Is_Processed__c***'+b.Is_Processed__c);
            
                if(b.ILT_Class__c != null && b.Voucher__c != null)
                {   
                    JSONWrapper.Students student = new JSONWrapper.Students();
                            
                    student.FirstName   = b.Student_First_Name__c;
                    student.LastName    = b.Student_Last_Name__c;
                    student.Email       = b.Student_Email_Address__c;
                    student.Phone       = b.Student_Phone_Number__c;
                    student.voucherid   = String.valueOf(b.Voucher__c).substring(0, 15);
                    student.Rosterid    = '';
    
                    theLearningPlanId   = b.ILT_Class__r.Learning_Plan__r.Id;
    
                    theOfferingId       = b.ILT_Class__r.Id;
    
                    studentList.add(student);
                }
                
                if(b.Learning__c != null && b.Voucher__c != null)
                {
                    JSONWrapper.Students student = new JSONWrapper.Students();
                            
                    student.FirstName   = b.Student_First_Name__c;
                    student.LastName    = b.Student_Last_Name__c;
                    student.Email       = b.Student_Email_Address__c;
                    student.Phone       = b.Student_Phone_Number__c;
                    student.voucherid   = String.valueOf(b.Voucher__c).substring(0, 15);
                    student.Rosterid    = '';
                    
                    if(!Test.isRunningTest())
                    {
                    	theLearningPlanId   = [select redwing__training_plan_section__r.redwing__Training_Plan__c from redwing__training_plan_section_item__c where redwing__learning__c =: (b.Learning__r.Id)].redwing__training_plan_section__r.redwing__Training_Plan__c;
                    }
    
                    theOfferingId       = b.Learning__r.Id;
                    
                    IsOnline	 		= true;
    
                    studentList.add(student);
                }
            
        }

        String JSONStudentList = JSON.serialize(studentList);
        System.debug('=======JSONAddStudents:'+JSONStudentList);
        System.debug('**theLearningPlanId**'+theLearningPlanId);

        if (theLearningPlanId != null && !Test.isRunningTest() && !IsOnline)
        {
            system.debug('***ILT Class***');
            ILTInstructorCommunity.enrollStudents(JSONStudentList, theLearningPlanId, theOfferingId, '', null);
        }
        
        if (IsOnline && !Test.isRunningTest())
        {
            system.debug('***Online Class***');
            ILTInstructorCommunity.enrollStudents(JSONStudentList, theLearningPlanId, theOfferingId, 'Online', null);
        }

    }

}