force-app/main/default/objects/Student_Bulk_Upload__c/Student_Bulk_Upload__c.object-meta.xml
<CustomObject>
    <label>Student Bulk Upload</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Student Bulk Upload Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Bulk Uploads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Bulk_Upload__c/fields/ILT_Class__c.field-meta.xml
<CustomField>
    <fullName>ILT_Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ILT Class</label>
    <referenceTo>redwing__ILT_Class__c</referenceTo>
    <relationshipLabel>Student Bulk Uploads</relationshipLabel>
    <relationshipName>Student_Bulk_Uploads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Bulk_Upload__c/fields/ILT_Class_Id__c.field-meta.xml
<CustomField>
    <fullName>ILT_Class_Id__c</fullName>
    <formula>ILT_Class__r.Id</formula>
    <label>ILT Class Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Bulk_Upload__c/fields/Learning__c.field-meta.xml
<CustomField>
    <fullName>Learning__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Learning</label>
    <referenceTo>redwing__Learning__c</referenceTo>
    <relationshipLabel>Student Bulk Uploads</relationshipLabel>
    <relationshipName>Student_Bulk_Uploads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Bulk_Upload__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>No ILT Class Found</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Bulk_Upload__c/fields/Student_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Student_First_Name__c</fullName>
    <label>Student First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Bulk_Upload__c/fields/Student_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Student_Last_Name__c</fullName>
    <label>Student Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Bulk_Upload__c/fields/Student_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Student_Phone_Number__c</fullName>
    <label>Student Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Student_Bulk_Upload__c/fields/Voucher__c.field-meta.xml
<CustomField>
    <fullName>Voucher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Voucher</label>
    <referenceTo>Voucher__c</referenceTo>
    <relationshipLabel>Student Bulk Uploads</relationshipLabel>
    <relationshipName>Student_Bulk_Uploads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <description>Store the Voucher required to enroll and register for a class</description>
    <label>Voucher</label>
    <nameField>
        <displayFormat>VN {000000}</displayFormat>
        <label>Voucher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voucher</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/fields/ILT_Class__c.field-meta.xml
<CustomField>
    <fullName>ILT_Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ILT Class</label>
    <referenceTo>redwing__ILT_Class__c</referenceTo>
    <relationshipLabel>Voucher</relationshipLabel>
    <relationshipName>Voucher</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Is_Assigned__c.field-meta.xml
<CustomField>
    <fullName>Is_Assigned__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Assigned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Online_Class__c.field-meta.xml
<CustomField>
    <fullName>Online_Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Online Class</label>
    <referenceTo>redwing__Learning__c</referenceTo>
    <relationshipLabel>Voucher</relationshipLabel>
    <relationshipName>Voucher</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Voucher</description>
    <inlineHelpText>Current Status of Voucher</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Issued</fullName>
                <default>true</default>
                <label>Issued</label>
            </value>
            <value>
                <fullName>Temp Hold</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Claimed</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
            <value>
                <fullName>Pending Cancellation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssignVouchersToBulkStudentBatch.cls
global class AssignVouchersToBulkStudentBatch implements Database.Batchable<sObject>, Database.Stateful
{
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        string query = 'SELECT Id, ILT_Class_Id__c, Learning__c, Status__c, Student_First_Name__c,Student_Last_Name__c,Student_Phone_Number__c FROM Student_Bulk_Upload__c WHERE Status__c != \'No ILT Class Found\' AND Voucher__c = null AND Is_Processed__c = false';

        //Student_Bulk_Upload__c sbu = [SELECT Id, ILT_Class__c, Status__c, Student_First_Name__c,Student_Last_Name__c,Student_Phone_Number__c FROM Student_Bulk_Upload__c WHERE Status__c != 'Success'];
        
        return Database.getQueryLocator(query);

    }

    global void execute(Database.BatchableContext BC, List<Student_Bulk_Upload__c> scope)
    {
        system.debug('scope***'+scope);
        List<Student_Bulk_Upload__c> studentsToUpdate = new List<Student_Bulk_Upload__c> ();

        for(Student_Bulk_Upload__c s : scope)
        {
            
            if(s.ILT_Class_Id__c != null)
            {
                system.debug('Inside ILT');
                s.Voucher__c = AssignVouchersToBulkStudentBatch.getVoucher(s.ILT_Class_Id__c);
                studentsToUpdate.add(s);
            }

            if(s.Learning__c != null)
            {
                system.debug('Inside Learning');
                s.Voucher__c = AssignVouchersToBulkStudentBatch.getVoucherForOnlineClass(s.Learning__c);
                studentsToUpdate.add(s);
            }
        }

        if(studentsToUpdate.size() > 0)
        {
            update studentsToUpdate;
        }

    }

    global void finish(Database.BatchableContext BC)
    {

    }

    public static Id getVoucher (Id ILTClassId)
    {
        if(ILTClassId != null)
        {
            Id  voucherId = [SELECT Id, Name, Status__c FROM Voucher__c WHERE Status__c = 'Issued' AND ILT_Class__r.Id =: ILTClassId AND Is_Assigned__c = false LIMIT 1].Id;

            if(voucherId != null)
            {
                Voucher__c v = new Voucher__c();
                v.Id             = voucherId;
                v.Is_Assigned__c = true;
                v.Status__c		 = 'Reserved';

                update v;

                return voucherId;
            }
            else
            {
                return null;
            }
        }
        else
        {
            return null;
        }
    }

    public static Id getVoucherForOnlineClass (Id learningId)
    {
        system.Debug('learningId***'+learningId);
        
        if(learningId != null)
        {
            Id  voucherId = [SELECT Id, Name, Status__c, ILT_Class__r.Id FROM Voucher__c WHERE Status__c = 'Issued' AND Online_Class__c =: learningId AND Is_Assigned__c = false LIMIT 1].Id;
            
            system.debug('voucherId***'+voucherId);

            if(voucherId != null)
            {
                Voucher__c v = new Voucher__c();
                v.Id             = voucherId;
                v.Is_Assigned__c = true;
                v.Status__c		 = 'Reserved';

                update v;

                return voucherId;
            }
            else
            {
                return null;
            }
        }
        else
        {
            return null;
        }
    }

}