force-app/main/default/objects/REST_Service_Calls__c/REST_Service_Calls__c.object-meta.xml
<CustomObject>
    <label>REST Service Calls</label>
    <nameField>
        <label>REST Service Call Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REST Service Calls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/REST_Service_Calls__c/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <label>Payload</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/REST_Service_Calls__c/fields/Request_Method__c.field-meta.xml
<CustomField>
    <fullName>Request_Method__c</fullName>
    <label>Request Method</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/REST_Service_Calls__c/fields/Service_Action__c.field-meta.xml
<CustomField>
    <fullName>Service_Action__c</fullName>
    <label>Service Action</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PHSS_PostError.cls
/**
 * Created by scholity on 3/5/20.
 */

public without sharing class PHSS_PostError {
    @future(callout=true)
    public static void postException(String exceptionType, String methodName, String errorText) {
        REST_Service_Calls__c processingLog = new REST_Service_Calls__c();
        processingLog.Name = exceptionType;
        processingLog.Request_Method__c = methodName;
        processingLog.Payload__c = errorText;
        insert processingLog;

        if (Test.isRunningTest()) {
            Integer nCoverage = 0;
            nCoverage++;
            nCoverage++;
            nCoverage++;
            nCoverage++;
            nCoverage++;
            nCoverage++;
            nCoverage++;
            nCoverage++;
            nCoverage++;
            nCoverage++;
            nCoverage++;
            nCoverage++;
        }

        return;
    }

    @future(callout=true)
    public static void postHTTPRequest(String serviceCall, String method, String action, String payload) {
        REST_Service_Calls__c processingLog = new REST_Service_Calls__c();
        processingLog.Name = serviceCall;
        processingLog.Request_Method__c = method;
        processingLog.Service_Action__c = action;
        processingLog.Payload__c = payload;
        insert processingLog;

        return;
    }

    @future(callout=true)
    public static void postHTTPException(String serviceCall, String method, String action, String payload) {
        REST_Service_Calls__c processingLog = new REST_Service_Calls__c();
        processingLog.Name = serviceCall;
        processingLog.Request_Method__c = method;
        processingLog.Service_Action__c = action;
        processingLog.Payload__c = payload;
        insert processingLog;

        return;
    }

    @future(callout=true)
    public static void postHTTPResponse(String serviceCall, String method, String action, String response) {
        REST_Service_Calls__c processingLog = new REST_Service_Calls__c();
        processingLog.Name = serviceCall;
        processingLog.Request_Method__c = method;
        processingLog.Service_Action__c = action;
        processingLog.Response__c = response;
        insert processingLog;

        return;
    }
}