force-app/main/default/objects/Bucket_Account_Settings__c/Bucket_Account_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Use this custom setting to configure the settings for the programmatic logic which assigns B2C contacts to bucket accounts. IMPORTANT: Do not create exceptions to the default org levels. Only configure the default org levels</description>
    <label>B2C Bucket Account Settings</label>
</CustomObject>

force-app/main/default/objects/Bucket_Account_Settings__c/fields/Bucket_Account_Owner_ID__c.field-meta.xml
<CustomField>
    <fullName>Bucket_Account_Owner_ID__c</fullName>
    <description>Specify the User ID of the User who will own bucket accounts. This user must be active. Note, changing this will not retroactively change the owner of bucket accounts already in the system.</description>
    <inlineHelpText>Specify the User ID of the User who will own bucket accounts. This user must be active. Note, changing this will not retroactively change the owner of bucket accounts already in the system.</inlineHelpText>
    <label>Bucket Account Owner ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bucket_Account_Settings__c/fields/Bucket_Account_RecordTypeID__c.field-meta.xml
<CustomField>
    <fullName>Bucket_Account_RecordTypeID__c</fullName>
    <description>Specify the record type of bucket accounts. Note, changing this will not retroactively change the record type of bucket accounts already in the system.</description>
    <inlineHelpText>Specify the record type of bucket accounts. Note, changing this will not retroactively change the record type of bucket accounts already in the system.</inlineHelpText>
    <label>Bucket Account RecordTypeID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bucket_Account_Settings__c/fields/Default_Bucket_Name__c.field-meta.xml
<CustomField>
    <fullName>Default_Bucket_Name__c</fullName>
    <description>Define the default account name for bucket accounts. Note, changing this will not retroactively change the name of bucket accounts already in the system.</description>
    <inlineHelpText>Define the default account name for bucket accounts. Note, changing this will not retroactively change the name of bucket accounts already in the system.</inlineHelpText>
    <label>Default Bucket Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bucket_Account_Settings__c/fields/Maximum_Size_of_Bucket__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Size_of_Bucket__c</fullName>
    <description>Define how many contacts a bucket account may contain before it is considered closed and may not accept any more contacts. Note if you change this value, then you must request that all B2C contacts are reassigned to buckets. This can be done by setting their AccountID to null. Triggers will catch on this criteria and reassign them to buckets based on the new threshold.</description>
    <label>Maximum Size of Bucket</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Sub_Type__c</fullName>
    <label>Case Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>2017 Rev/Chal Price Change</fullName>
            </value>
            <value>
                <fullName>2018 AP/LTP Price Increase</fullName>
            </value>
            <value>
                <fullName>Abandoned in Portal</fullName>
            </value>
            <value>
                <fullName>Age requirement</fullName>
            </value>
            <value>
                <fullName>AHA Crossover</fullName>
            </value>
            <value>
                <fullName>Annual AP/LTP Price Increase</fullName>
            </value>
            <value>
                <fullName>AP/LTP – Blended Learning</fullName>
            </value>
            <value>
                <fullName>AP/LTP – Classroom</fullName>
            </value>
            <value>
                <fullName>Application &amp; Registration Fees Paid</fullName>
            </value>
            <value>
                <fullName>Application Fee paid</fullName>
            </value>
            <value>
                <fullName>Application Info sent to customer</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>AP Scheduling Tool</fullName>
            </value>
            <value>
                <fullName>Aquatics Examiner Service.</fullName>
            </value>
            <value>
                <fullName>Authorized Provider</fullName>
            </value>
            <value>
                <fullName>Blended Learning</fullName>
            </value>
            <value>
                <fullName>Blood</fullName>
            </value>
            <value>
                <fullName>Bridging</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Canceled CRS</fullName>
            </value>
            <value>
                <fullName>Cardio</fullName>
            </value>
            <value>
                <fullName>Careers</fullName>
            </value>
            <value>
                <fullName>Centennial Program</fullName>
            </value>
            <value>
                <fullName>Certifications</fullName>
            </value>
            <value>
                <fullName>CEU Class</fullName>
            </value>
            <value>
                <fullName>Charged incorrect price</fullName>
            </value>
            <value>
                <fullName>Cintas</fullName>
            </value>
            <value>
                <fullName>CNA Prep Course</fullName>
            </value>
            <value>
                <fullName>Community Cancellation</fullName>
            </value>
            <value>
                <fullName>Community Offerings on RCO</fullName>
            </value>
            <value>
                <fullName>Lifeguarding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Contract.recordType-meta.xml
<RecordType>
    <fullName>Contract</fullName>
    <active>true</active>
    <businessProcess>AID Inc</businessProcess>
    <description>Manage the Opportunity Contract Process</description>
    <label>Contract</label>
</RecordType>

force-app/main/default/objects/Switch__c/Switch__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Switch</label>
</CustomObject>

force-app/main/default/objects/Switch__c/fields/Switch__c.field-meta.xml
<CustomField>
    <fullName>Switch__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Switch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/GarbageAccountBatchTest.cls
/*****************************************************************************************************
 
Class    :  GarbageAccountBatchTest
Developer:  Sudhir.
Created  :  Aug 14, 2019
Modified :  Aug 14, 2019
Objective:  This class is used to test the class GarbageAccountBatch
 
*****************************************************************************************************/ 
@isTest
private class GarbageAccountBatchTest {
    @testSetup static void methodName() {
        Switch__c cohstest = new Switch__c();
            cohstest.Switch__c = true;
            cohstest.name = 'CaseOwnerHistorySwitch';
            insert cohstest;
            
            //for Custom Setting
            Bucket_Account_Settings__c supportConfig = Bucket_Account_Settings__c.getOrgDefaults();
            supportConfig.Bucket_Account_Owner_ID__c = '005d0000001WOeV'; 
            supportConfig.Bucket_Account_RecordTypeID__c = '012d000000098Wt';
            supportConfig.Default_Bucket_Name__c = 'Bucket Account';
            supportConfig.Maximum_Size_of_Bucket__c =   5000;       
            insert supportConfig;
                                  
            //Datetime yesterday = Datetime.now().addDays(-500);
            
                
            /*List<Account> AccList=new List<Account>();
            List<Contact> ConList=new List<Contact>();
            List<Attachment> AttList =new List<Attachment>();
            List<Note> NotesList=new List<Note>();
            List<Task> TasksList=new List<Task>();
            List<Event> EventsList=new List<Event>();
            List<Opportunity> OppList=new List<Opportunity>();
            List<Case> CaseList=new List<Case>();
            List<AccountContactRole> AcconList=new List<AccountContactRole>();
            List<Contract> ContraList=new List<Contract>();
            
            for(Integer i=1;i<10;i++)
            {
                AccList.add(new Account(Name = 'Test'+i));
            }
            insert AccList;
            
            Integer j=1;
            for(Account Acc:AccList)
            {
                Test.setCreatedDate(Acc.Id, yesterday);
                ConList.add(new Contact(FirstName = 'Test'+j,LastName = 'Contact',accountId =Acc.Id));
                //AttList.add(new Attachment(Name = 'fileName',ParentId=Acc.Id));
                OppList.add(new Opportunity(Name = 'Test'+j,accountId =Acc.Id,Type = 'Retail',StageName='Approch',CloseDate=system.today()+2));
                //CaseList.add(new Case(Type = 'Aquatics'+j,Case_Sub_Type__c = 'Lifeguarding',accountId =Acc.Id));
                j++;
            }*/
            Account Accs = new Account(Name = 'Test');
            insert Accs;
            Datetime yesterday = Datetime.now().addDays(-500);
            Test.setCreatedDate(Accs.Id, yesterday);
            Contact Cons = new Contact(FirstName = 'Test',LastName = 'Contact',accountId =Accs.Id);
            insert Cons;
            Case Casess=new Case();
            /*Casess.Type = 'Aquatics';
            Casess.Case_Sub_Type__c = 'Lifeguarding';
            Casess.ContactId = Cons.Id;
            Casess.AccountId = Cons.AccountId;
            insert Casess;*/
    }  
    private static testMethod void testBatch()
    {
        Test.startTest();
        GarbageAccountBatch GbAcc=new GarbageAccountBatch();
           Id BatchId = Database.executeBatch(GbAcc);
        Test.stopTest();
 
    } 
    /*private static testMethod void testBatc1()
    {
        final String CREATED_DATE_FIELD = String.valueof(Date.today()-30);
        Test.startTest();
           Id BatchId1 = Database.executeBatch(new GarbageAccountBatch(CREATED_DATE_FIELD), 50);
        Test.stopTest();
 
    } */
}