force-app/main/default/objects/Account/fields/DM_External_Id__c.field-meta.xml
<CustomField>
    <fullName>DM_External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>This field is utilized to support the data migration process.  It will contain a combination of the source system identifier and the source system&#39;s unique record identifier.  This field should be deleted after all migration activities are complete.</description>
    <externalId>true</externalId>
    <label>DM External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Bucket_Account_Settings__c/Bucket_Account_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Use this custom setting to configure the settings for the programmatic logic which assigns B2C contacts to bucket accounts. IMPORTANT: Do not create exceptions to the default org levels. Only configure the default org levels</description>
    <label>B2C Bucket Account Settings</label>
</CustomObject>

force-app/main/default/objects/Bucket_Account_Settings__c/fields/Bucket_Account_Owner_ID__c.field-meta.xml
<CustomField>
    <fullName>Bucket_Account_Owner_ID__c</fullName>
    <description>Specify the User ID of the User who will own bucket accounts. This user must be active. Note, changing this will not retroactively change the owner of bucket accounts already in the system.</description>
    <inlineHelpText>Specify the User ID of the User who will own bucket accounts. This user must be active. Note, changing this will not retroactively change the owner of bucket accounts already in the system.</inlineHelpText>
    <label>Bucket Account Owner ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bucket_Account_Settings__c/fields/Bucket_Account_RecordTypeID__c.field-meta.xml
<CustomField>
    <fullName>Bucket_Account_RecordTypeID__c</fullName>
    <description>Specify the record type of bucket accounts. Note, changing this will not retroactively change the record type of bucket accounts already in the system.</description>
    <inlineHelpText>Specify the record type of bucket accounts. Note, changing this will not retroactively change the record type of bucket accounts already in the system.</inlineHelpText>
    <label>Bucket Account RecordTypeID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bucket_Account_Settings__c/fields/Default_Bucket_Name__c.field-meta.xml
<CustomField>
    <fullName>Default_Bucket_Name__c</fullName>
    <description>Define the default account name for bucket accounts. Note, changing this will not retroactively change the name of bucket accounts already in the system.</description>
    <inlineHelpText>Define the default account name for bucket accounts. Note, changing this will not retroactively change the name of bucket accounts already in the system.</inlineHelpText>
    <label>Default Bucket Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bucket_Account_Settings__c/fields/Maximum_Size_of_Bucket__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Size_of_Bucket__c</fullName>
    <description>Define how many contacts a bucket account may contain before it is considered closed and may not accept any more contacts. Note if you change this value, then you must request that all B2C contacts are reassigned to buckets. This can be done by setting their AccountID to null. Triggers will catch on this criteria and reassign them to buckets based on the new threshold.</description>
    <label>Maximum Size of Bucket</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/DM_External_Id__c.field-meta.xml
<CustomField>
    <fullName>DM_External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>This field is utilized to support the data migration process. It will contain a combination of the source system identifier and the source system&#39;s unique record identifier. This field should be deleted after all migration activities are complete</description>
    <externalId>true</externalId>
    <label>DM External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/DM_External_Id__c.field-meta.xml
<CustomField>
    <fullName>DM_External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>This field is utilized to support the data migration process.  It will contain a combination of the source system identifier and the source system&#39;s unique record identifier.  This field should be deleted after all migration activities are complete.</description>
    <externalId>true</externalId>
    <inlineHelpText>This field is utilized to support the data migration process.  It will contain a combination of the source system identifier and the source system&#39;s unique record identifier.  This field should be deleted after all migration activities are complete.</inlineHelpText>
    <label>DM External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ProfileUpdateTest.cls
@isTest
public class ProfileUpdateTest
{
    
    /*@testSetup 
    public static void initTestData()
    {
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('SB Organization Account').getRecordTypeId();
        
        Account a = new Account();
        a.Name='SalesforcetestOrg';
        a.DM_External_Id__c ='SalesforcetestOrgtest@test.com';
        a.BillingStreet='24 Willie Mays Plaza';
        a.BillingCity='San Francisco';
        a.BillingState='California';
        a.BillingPostalCode='94017';
        a.BillingCountry='USA';
        a.Phone='9934200234';
        a.recordTypeId = recordTypeId;
        insert a;
        
        //Bucket Custom settings
        Bucket_Account_Settings__c bas = Bucket_Account_Settings__c.getOrgDefaults();
        bas.Bucket_Account_Owner_ID__c = UserInfo.getUserID();
        bas.Bucket_Account_RecordTypeID__c = recordTypeId;
        bas.Default_Bucket_Name__c = 'Bucket Account';
        bas.Maximum_Size_of_Bucket__c = 5000;
        insert bas;
        
        Contact con = new Contact();
        con.FirstName = 'Test';
        con.LastName = 'SalesforcetestOrg';
        con.Email = 'test@test.com';
        con.AccountId = a.id;
        con.NSSCCConnector__Contact_Status__c = 'Created';
        insert con;
        
        User u = new User();
        u.FirstName = 'Admin';
        u.LastName = 'User';
        u.Alias = 'admu';
        u.Email = 'admin@user.usr';
        u.Username = '232343admin@user.de';
        u.ProfileId = [SELECT Id FROM Profile WHERE Name = 'SB PHSS-IC-Community Plus Login' LIMIT 1].Id;
        u.TimeZoneSidKey = 'America/Los_Angeles';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.LocaleSidKey = 'en_US';
        u.contactId = con.Id;
        insert u;
        
    }*/
    
    static testMethod void testProfileUpdate ()
    {
        Profile p = [SELECT Id FROM Profile WHERE Name     = 'SB PHSS-IC-Community Plus Login' LIMIT 1];
        User u 	  = [SELECT Id FROM User    WHERE IsActive = true AND ContactId != null AND Profile.Name != 'SB PHSS-IC-Community Plus Login' LIMIT 1];
        
        test.startTest();
        	ProfileUpdate.updateProfile(p.Id, u.Id);
        test.stopTest();
        
    }

}