force-app/main/default/objects/Account/fields/Open_Order_Amount__c.field-meta.xml
<CustomField>
    <fullName>Open_Order_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Sum of Orders In Process</description>
    <label>Open Order Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Bucket_Account_Settings__c/Bucket_Account_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Use this custom setting to configure the settings for the programmatic logic which assigns B2C contacts to bucket accounts. IMPORTANT: Do not create exceptions to the default org levels. Only configure the default org levels</description>
    <label>B2C Bucket Account Settings</label>
</CustomObject>

force-app/main/default/objects/Bucket_Account_Settings__c/fields/Bucket_Account_Owner_ID__c.field-meta.xml
<CustomField>
    <fullName>Bucket_Account_Owner_ID__c</fullName>
    <description>Specify the User ID of the User who will own bucket accounts. This user must be active. Note, changing this will not retroactively change the owner of bucket accounts already in the system.</description>
    <inlineHelpText>Specify the User ID of the User who will own bucket accounts. This user must be active. Note, changing this will not retroactively change the owner of bucket accounts already in the system.</inlineHelpText>
    <label>Bucket Account Owner ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bucket_Account_Settings__c/fields/Bucket_Account_RecordTypeID__c.field-meta.xml
<CustomField>
    <fullName>Bucket_Account_RecordTypeID__c</fullName>
    <description>Specify the record type of bucket accounts. Note, changing this will not retroactively change the record type of bucket accounts already in the system.</description>
    <inlineHelpText>Specify the record type of bucket accounts. Note, changing this will not retroactively change the record type of bucket accounts already in the system.</inlineHelpText>
    <label>Bucket Account RecordTypeID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bucket_Account_Settings__c/fields/Default_Bucket_Name__c.field-meta.xml
<CustomField>
    <fullName>Default_Bucket_Name__c</fullName>
    <description>Define the default account name for bucket accounts. Note, changing this will not retroactively change the name of bucket accounts already in the system.</description>
    <inlineHelpText>Define the default account name for bucket accounts. Note, changing this will not retroactively change the name of bucket accounts already in the system.</inlineHelpText>
    <label>Default Bucket Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bucket_Account_Settings__c/fields/Maximum_Size_of_Bucket__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Size_of_Bucket__c</fullName>
    <description>Define how many contacts a bucket account may contain before it is considered closed and may not accept any more contacts. Note if you change this value, then you must request that all B2C contacts are reassigned to buckets. This can be done by setting their AccountID to null. Triggers will catch on this criteria and reassign them to buckets based on the new threshold.</description>
    <label>Maximum Size of Bucket</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AccountContactRelationTriggerHandlerTest.cls
@isTest(SeeAllData=false)
public with sharing class AccountContactRelationTriggerHandlerTest {
    
    private static User testUser;

    private static Contact testContact;

    private static Account testAccount;

    private static Profile learnerProfile = [SELECT Id FROM Profile WHERE Name = 'Learner Community Profile' LIMIT 1];
    
    private static void generateTestData(){

        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Bucket Account').getRecordTypeId();
        
        //Bucket Custom settings
        Bucket_Account_Settings__c bas = Bucket_Account_Settings__c.getOrgDefaults();
        bas.Bucket_Account_Owner_ID__c = UserInfo.getUserID();
        bas.Bucket_Account_RecordTypeID__c = recordTypeId;
        bas.Default_Bucket_Name__c = 'Bucket Account';
        bas.Maximum_Size_of_Bucket__c = 5000;
        insert bas;

        testAccount = new Account(
            Name='SalesforcetestOrg1',
            BillingStreet='24 Willie Mays Plaza',
            BillingCity='San Francisco',
            BillingState='California',
            BillingPostalCode='94017',
            BillingCountry='USA',
            Phone='9934200234',
            Open_Order_Amount__c = 1        
        );
        insert testAccount;
        
        testContact = new Contact(
            FirstName = 'test',
            LastName = 'learneruser',
            Email = 'learneruser@321test123fake.net',
            AccountId = testAccount.Id
        );
        insert testContact;
        
        testUser = new User(
            Alias = 'newUser', 
            Email ='newuser@testorg.com',
            EmailEncodingKey = 'UTF-8',
            FirstName = 'test',
            LastName = 'learneruser', 
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US', 
            ProfileId = learnerProfile.Id, 
            ContactId = testContact.Id,
            TimeZoneSidKey = 'America/Los_Angeles', 
            UserName = 'learneruser@321test123fake.net'
        );
        insert testUser;        
    }

    @isTest static void testUpdateInstructorProfiles(){

        generateTestData();

        Test.StartTest();

        AccountContactRelation testAccountContactRelation = [SELECT Id, Roles FROM AccountContactRelation WHERE AccountId = :testAccount.Id AND ContactId = :testContact.Id LIMIT 1];

        system.assertNotEquals(testAccountContactRelation, null);

        testAccountContactRelation.Roles = 
            String.isBlank(testAccountContactRelation.Roles) ? 
            AccountContactRelationTriggerHandler.ACR_ROLE_INSTRUCTOR : 
            (testAccountContactRelation.Roles+';'+AccountContactRelationTriggerHandler.ACR_ROLE_INSTRUCTOR);

        update testAccountContactRelation;

        Test.stopTest();

        testUser = [SELECT Id, ProfileId, UserRole.Name FROM User WHERE Id = :testUser.Id];

        system.debug('@@@testUser: '+testUser);
        
        system.assertEquals(testUser.ProfileId, AccountContactRelationTriggerHandler.instructorProfile.Id);

    }

    @isTest static void testUpdateAdminProfiles(){

        generateTestData();

        Test.StartTest();

        AccountContactRelation testAccountContactRelation = [SELECT Id, Roles FROM AccountContactRelation WHERE AccountId = :testAccount.Id AND ContactId = :testContact.Id LIMIT 1];

        system.assertNotEquals(testAccountContactRelation, null);

        testAccountContactRelation.Roles = 
            String.isBlank(testAccountContactRelation.Roles) ? 
            AccountContactRelationTriggerHandler.ACR_ROLE_ADMINISTRATOR : 
            (testAccountContactRelation.Roles+';'+AccountContactRelationTriggerHandler.ACR_ROLE_ADMINISTRATOR);

        update testAccountContactRelation;

        Test.stopTest();

        testUser = [SELECT Id, ProfileId, UserRole.Name FROM User WHERE Id = :testUser.Id];
        
        system.assertEquals(testUser.ProfileId, AccountContactRelationTriggerHandler.adminProfile.Id);

    }
}