force-app/main/default/objects/Channel_Compensation__c/Channel_Compensation__c.object-meta.xml
<CustomObject>
    <description>This object is intended to hold data from our financials system for compensation purposes and integrate with xactly external tool</description>
    <label>Training Revenue</label>
    <nameField>
        <displayFormat>CHNC{0000000000}</displayFormat>
        <label>Channel Compensation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Revenue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Compensation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Training Revenue</relationshipLabel>
    <relationshipName>Training_Revenue</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Channel_Compensation__c/fields/BATCH_Id__c.field-meta.xml
<CustomField>
    <fullName>BATCH_Id__c</fullName>
    <label>BATCH Id</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Channel_Compensation__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel_Compensation__c/fields/Fiscal_Month_Abbr__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Month_Abbr__c</fullName>
    <label>Fiscal Month Abbr</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel_Compensation__c/fields/FOCIS_Category__c.field-meta.xml
<CustomField>
    <fullName>FOCIS_Category__c</fullName>
    <label>PSC Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel_Compensation__c/fields/Focis_Location__c.field-meta.xml
<CustomField>
    <fullName>Focis_Location__c</fullName>
    <label>BGST</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel_Compensation__c/fields/Focis_Program__c.field-meta.xml
<CustomField>
    <fullName>Focis_Program__c</fullName>
    <label>Product 3</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel_Compensation__c/fields/FOCIS_Subject_Area__c.field-meta.xml
<CustomField>
    <fullName>FOCIS_Subject_Area__c</fullName>
    <label>Product SKU</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel_Compensation__c/fields/Fulfillment_Item__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The transaction item the Training Revenue record is based on</description>
    <inlineHelpText>The transaction item the Training Revenue record is based on</inlineHelpText>
    <label>Fulfillment Item</label>
    <referenceTo>Fulfillment_Item__c</referenceTo>
    <relationshipLabel>Training Revenue</relationshipLabel>
    <relationshipName>Training_Revenue</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Channel_Compensation__c/fields/Org_Id__c.field-meta.xml
<CustomField>
    <fullName>Org_Id__c</fullName>
    <label>Org Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel_Compensation__c/fields/Org_Type__c.field-meta.xml
<CustomField>
    <fullName>Org_Type__c</fullName>
    <description>Possible Types: AP, FS, CO, LTP</description>
    <label>Org Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel_Compensation__c/fields/Registration_Count__c.field-meta.xml
<CustomField>
    <fullName>Registration_Count__c</fullName>
    <label>Registration Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Channel_Compensation__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel_Compensation__c/fields/SubPG__c.field-meta.xml
<CustomField>
    <fullName>SubPG__c</fullName>
    <label>Product 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel_Compensation__c/fields/Transaction_Amt__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Amt__c</fullName>
    <label>Transaction Amt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Channel_Compensation__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <label>Zip Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fulfillment__c/Fulfillment__c.object-meta.xml
<CustomObject>
    <description>This object will hold the fulfillment information for Training and Credits. The data in this object is used to create Invoices and Credit Memos (CC Invoice records).</description>
    <label>Fulfillment</label>
    <nameField>
        <displayFormat>F-{0000000}</displayFormat>
        <label>Fulfillment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fulfillment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>CC Order Account Name</description>
    <formula>Order__r.ccrz__Account__r.Name</formula>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fulfillment__c/fields/Channel_Formula__c.field-meta.xml
<CustomField>
    <fullName>Channel_Formula__c</fullName>
    <formula>CASE(  FOCIS_Category__c  , 
&#39;42&#39;, &#39;FS&#39;, 
&#39;43&#39;, &#39;AP/LTP&#39;, 
&#39;45&#39;, &#39;CPS&#39;, 
&#39;46&#39;, &#39;COM-RCO&#39;, 
&#39;47&#39;, &#39;COM-ITM&#39;, 
&#39;48&#39;, &#39;COM-RCO&#39;, 
&#39;Other&#39;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Channel Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fulfillment__c/fields/FOCIS_Category__c.field-meta.xml
<CustomField>
    <fullName>FOCIS_Category__c</fullName>
    <formula>Order__r.FOCIS_Category__c</formula>
    <label>FOCIS Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fulfillment__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Order fulfilled</description>
    <label>Order</label>
    <referenceTo>ccrz__E_Order__c</referenceTo>
    <relationshipLabel>Fulfillments</relationshipLabel>
    <relationshipName>Fulfillments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fulfillment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of fulfillment</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fulfillment_Item__c/Fulfillment_Item__c.object-meta.xml
<CustomObject>
    <description>This object will hold the fulfillment information information for Training and Products. The data in this object is used to create CC Invoice Item records.</description>
    <label>Fulfillment Item</label>
    <nameField>
        <displayFormat>FI-{0000000}</displayFormat>
        <label>Fulfillment Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillment Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fulfillment_Item__c/fields/CC_Product__c.field-meta.xml
<CustomField>
    <fullName>CC_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>CC Product</label>
    <referenceTo>ccrz__E_Product__c</referenceTo>
    <relationshipLabel>Fulfillment Items</relationshipLabel>
    <relationshipName>Fulfillment_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fulfillment_Item__c/fields/Fulfillment__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment__c</fullName>
    <description>Parent record</description>
    <label>Fulfillment</label>
    <referenceTo>Fulfillment__c</referenceTo>
    <relationshipLabel>Fulfillment Items</relationshipLabel>
    <relationshipName>Fulfillment_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fulfillment_Item__c/fields/Fulfillment_Date__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_Date__c</fullName>
    <description>Date when the Fulfillment Item is set to Complete</description>
    <inlineHelpText>Date when the Fulfillment Item is set to Complete</inlineHelpText>
    <label>Fulfillment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Fulfillment_Item__c/fields/Fulfillment_Item_Total__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_Item_Total__c</fullName>
    <description>Order Item Price * Fulfillment Item Quantity</description>
    <formula>Order_Item__r.ccrz__Price__c  *  Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Order Item Price * Fulfillment Item Quantity</inlineHelpText>
    <label>Fulfillment Item Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fulfillment_Item__c/fields/Opportunity_Owner_Email__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Owner_Email__c</fullName>
    <formula>Order__r.Opportunity_Order__r.Owner.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Owner Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fulfillment_Item__c/fields/Opportunity_Profile__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Profile__c</fullName>
    <formula>IF(CONTAINS( Order__r.Opportunity_Order__r.Owner_Profile__c , &#39;BGST&#39;) , &#39;BGST&#39;, &#39;&#39;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Profile</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fulfillment_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Order to be fulfilled</description>
    <label>Order</label>
    <referenceTo>ccrz__E_Order__c</referenceTo>
    <relationshipLabel>Fulfillment Items</relationshipLabel>
    <relationshipName>Fulfillment_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fulfillment_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fulfillment_Item__c/fields/State_Formula__c.field-meta.xml
<CustomField>
    <fullName>State_Formula__c</fullName>
    <description>Set state value for Training Revenue</description>
    <formula>IF(  AND(!ISNULL(ILT_Class__c), Order__r.ccrz__Storefront__c &lt;&gt; &quot;CREStore&quot;), 
 IF(
    AND(!ISNULL(ILT_Class__r.Skedulo_Job_Id__c), !ISNULL( ILT_Class__r.Location_State__c )),
    ILT_Class__r.Location_State__c, Order__r.ccrz__Account__r.BillingState ) ,Order__r.ccrz__Account__r.BillingState)</formula>
    <label>State Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fulfillment_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the fulfillment item</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
                <default>true</default>
                <label>Ready</label>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fulfillment_Item__c/fields/Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date__c</fullName>
    <description>This field holds the date the item is ready for invoicing. Used to create CFS file.</description>
    <label>Transaction Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Fulfillment_Item__c/fields/Zip_Formula__c.field-meta.xml
<CustomField>
    <fullName>Zip_Formula__c</fullName>
    <formula>/*IF(  AND(!ISBLANK(ILT_Class__c), Order__r.ccrz__Storefront__c &lt;&gt; &quot;CREStore&quot;), 
 IF(
    AND(!ISBLANK(ILT_Class__r.Skedulo_Job_Id__c), !ISBLANK( ILT_Class__r.Location_ZIP_Code__c )),
     ILT_Class__r.Location_ZIP_Code__c ,  Order__r.ccrz__Account__r.BillingPostalCode  ) ,Order__r.ccrz__Account__r.BillingPostalCode)*/

 IF(!ISBLANK(Order__r.ccrz__Account__r.ShippingPostalCode), Order__r.ccrz__Account__r.ShippingPostalCode, 
  IF(!ISBLANK(Order__r.ccrz__Account__r.BillingPostalCode), Order__r.ccrz__Account__r.BillingPostalCode,
   IF(!ISBLANK(ILT_Class__r.Location_ZIP_Code__c), ILT_Class__r.Location_ZIP_Code__c, &quot;00000&quot;) ) )</formula>
    <label>Zip Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreateTrainingRevenueBatch.cls
global class CreateTrainingRevenueBatch implements Database.Batchable<sObject>
{
    @testVisible
    private static final String FULFILLMENT_ITEM_STATUS_INVOICED = 'Invoiced';
	
    @testVisible
    private static map<Integer, String> fiscalMothAbbreviationMap = new Map<Integer, String>
    {
        1 => 'JAN', 2 => 'FEB', 3 => 'MAR', 4 => 'APR',
        5 => 'MAY', 6 => 'JUN', 7 => 'JUL', 8 => 'AUG',
        9 => 'SEP', 10=> 'OCT', 11=> 'NOV', 12=> 'DEC'
    };
        
    global Database.QueryLocator start(Database.BatchableContext bc)
    {
        //SELECT Id FROM Fulfillment_Item__c WHERE Status__c = 'Invoiced'
        
        String query = 'SELECT 	Id,' 											+
                                'Order__r.ccrz__Account__c,' 					+
                                'Fulfillment__r.Channel_Formula__c,' 			+
                                'Order__r.ccrz__Storefront__c,' 				+
                                'Transaction_Date__c,' 							+
                                'Fulfillment__r.FOCIS_Category__c,' 			+
                                'CC_Product__r.ccrz__SKU__c,' 					+
                                'Opportunity_Profile__c,' 						+
                                'CC_Product__r.Product_3__c,' 					+
                                'Order__r.ccrz__Account__r.SABA_LMS_Code__c,' 	+
                                'Order__r.ccrz__Account__r.Name,' 				+
                                'Order__r.ccrz__Account__r.SABA_Org_Type__c,' 	+
                                'Quantity__c,' 									+
                                'State_Formula__c,' 							+
                                'CC_Product__r.Product_2__c,' 					+
                                'Fulfillment_Item_Total__c,' 					+
                                'Opportunity_Owner_Email__c,' 					+
                                'Zip_Formula__c '								+
            			   'FROM Fulfillment_Item__c '							+
            			  'WHERE Status__c = \'Invoiced\'';
        
        system.debug(query);
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<Fulfillment_Item__c> scope)
    {
        system.debug('***scope***'+scope);
        
        List<Channel_Compensation__c> trainingRevenueRecordsToInsert = new List<Channel_Compensation__c>();
        List<Fulfillment_Item__c>	fulfillmentItemsToUpdate		 = new List<Fulfillment_Item__c>();
        
        for(Fulfillment_Item__c fi : scope)
        {
            trainingRevenueRecordsToInsert.add(
                new Channel_Compensation__c(
                    Account__c 				= fi.Order__r.ccrz__Account__c,
                    //BATCH_Id__c 			= fi.Fulfillment_Date__c,
                    BATCH_Id__c 			= date.today(),
                    Channel__c 				= (fi.Fulfillment__c != null ? fi.Fulfillment__r.Channel_Formula__c : null),
                    Data_Source__c 			= fi.Order__r.ccrz__Storefront__c,
                    End_Date__c 			= Date.valueOf(fi.Transaction_Date__c),
                    FOCIS_Category__c 		= (fi.Fulfillment__c != null ? fi.Fulfillment__r.FOCIS_Category__c : null),
                    FOCIS_Subject_Area__c 	= fi.CC_Product__r.ccrz__SKU__c,
                    //Fiscal_Month_Abbr__c 	= fiscalMothAbbreviationMap.get(fi.Fulfillment_Date__c.month()),
                    Fiscal_Month_Abbr__c 	= fiscalMothAbbreviationMap.get(date.today().month()),
                    Focis_Location__c 		= fi.Opportunity_Profile__c,
                    Focis_Program__c 		= fi.CC_Product__r.Product_3__c,
                    Fulfillment_Item__c		= fi.Id,
                    Org_Id__c 				= (String.isNotBlank(fi.Order__r.ccrz__Account__r.SABA_LMS_Code__c) ? fi.Order__r.ccrz__Account__r.SABA_LMS_Code__c : null),
                    Org_Name__c 			= fi.Order__r.ccrz__Account__r.Name,
                    Org_Type__c 			= fi.Order__r.ccrz__Account__r.SABA_Org_Type__c,
                    Registration_Count__c 	= fi.Quantity__c,
                    State__c 				= fi.State_Formula__c,
                    SubPG__c 				= fi.CC_Product__r.Product_2__c,
                    Transaction_Amt__c 		= fi.Fulfillment_Item_Total__c,
                    User_Field__c 			= fi.Opportunity_Owner_Email__c,
                    Zip_Code__c 			= fi.Zip_Formula__c
                )
            );
            
            fi.Status__c 					= 'Complete';
            
            fulfillmentItemsToUpdate.add(fi);
        }
        
        insert(trainingRevenueRecordsToInsert);
        update(fulfillmentItemsToUpdate);
    }
    
    global void finish(Database.BatchableContext bc)
    {
        //Add email logic to sent email on complition
    }    
}